/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
package com.dell.isg.smi.virtualnetwork.exception;

import com.dell.isg.smi.commons.elm.messaging.IMessageEnum;

/**
 * The Enum ErrorCodeEnum.
 */
public enum ErrorCodeEnum implements IMessageEnum {
    ENUM_INVALID_DATA("ENUM_INVALID_DATA", 200002), ENUM_INVALIDINPUT_ERROR("ENUM_INVALIDINPUT_ERROR", 200005), ENUM_BAD_REQUEST_ERROR("ENUM_BAD_REQUEST_ERROR", 200400), ENUM_NOT_FOUND_ERROR("ENUM_NOT_FOUND_ERROR", 200404), NETWORKCONF_SYSTEM_ERROR("NETWORKCONF_SYSTEM_ERROR", 232002), NETWORKCONF_CANNOT_BE_STATIC("NETWORKCONF_CANNOT_BE_STATIC", 232006), NETWORKCONF_MUST_BE_STATIC("NETWORKCONF_MUST_BE_STATIC", 232007), NETWORKCONF_NETWORK_MISMATCH("NETWORKCONF_NETWORK_MISMATCH", 232008), NETWORKCONF_IP_IN_USE("NETWORKCONF_IP_IN_USE", 232009), NETWORKCONF_EMPTY_NETWORKNAME("NETWORKCONF_EMPTY_NETWORKNAME", 232010), NETWORKCONF_VLANID_OUTOF_RANGE("NETWORKCONF_VLANID_OUTOF_RANGE", 232012), NETWORKCONF_INVALIDNETWORK_TYPE("NETWORKCONF_INVALIDNETWORK_TYPE", 232013), NETWORKCONF_VLANID_CANOT_BE_NULL("NETWORKCONF_VLANID_CANOT_BE_NULL", 232014), NETWORKCONF_VLANID_MUST_BE_NULL("NETWORKCONF_VLANID_MUST_BE_NULL", 232015), NETWORKCONF_IP_RANGE_LIMIT_EXCEEDED("NETWORKCONF_IP_RANGE_LIMIT_EXCEEDED", 232016), NETWORKCONF_INVALID_NETWORK_CONF("NETWORKCONF_INVALID_NETWORK_CONF", 232017), NETWORKCONF_IPADDRESS_TYPE_CHANGED("NETWORKCONF_IPADDRESS_TYPE_CHANGED", 232018), NETWORKCONF_NETWORK_OVERLAP("NETWORKCONF_NETWORK_OVERLAP", 232019), NETWORKCONF_INVALID_IP_FOR_PRIMARY_DNS("NETWORKCONF_INVALID_IP_FOR_PRIMARY_DNS", 232024), NETWORKCONF_INVALID_IP_FOR_SECONDARY_DNS("NETWORKCONF_INVALID_IP_FOR_SECONDARY_DNS", 232025), NETWORKCONF_SAME_PRIMARY_SECONDARY_DNS("NETWORKCONF_SAME_PRIMARY_SECONDARY_DNS", 232026), NETWORKCONF_EMPTY_GATEWAY("NETWORKCONF_EMPTY_GATEWAY", 232027), NETWORKCONF_INVALID_IP_FOR_GATEWAY("NETWORKCONF_INVALID_IP_FOR_GATEWAY", 232028), NETWORKCONF_INVALID_SUBNET_IP("NETWORKCONF_INVALID_SUBNET_IP", 232035), NETWORKCONF_INVALID_DNS_SUFFIX("NETWORKCONF_INVALID_DNS_SUFFIX", 232029), NETWORKCONF_GATEWAY_SUBNET_IPRANGE_NOT_SAME("NETWORKCONF_GATEWAY_SUBNET_IPRANGE_NOT_SAME", 232030), NETWORKCONF_INVALID_IPRANGE("NETWORKCONF_INVALID_IPRANGE", 232031), NETWORKCONF_OVERLAP_IPRANGE("NETWORKCONF_OVERLAP_IPRANGE", 232032), NETWORKCONF_INVALID_IPRANGE_START_IP("NETWORKCONF_INVALID_IPRANGE_START_IP", 232033), NETWORKCONF_INVALID_IPRANGE_END_IP("NETWORKCONF_INVALID_IPRANGE_END_IP", 232034), NETWORKCONF_IPRANGE_SAVE_OR_UPDATE_FAILED("NETWORKCONF_IPRANGE_SAVE_OR_UPDATE_FAILED", 232036), NETWORKCONF_IPRANGE_UPDATE_FAILED_IP_IN_USE("NETWORKCONF_IPRANGE_UPDATE_FAILED_IP_IN_USE", 232037), NETWORKCONF_IPRANGE_DELETE_FAILED("NETWORKCONF_IPRANGE_DELETE_FAILED", 232038), NETWORKCONF_IPRANGE_NOT_FOUND("NETWORKCONF_IPRANGE_NOT_FOUND", 232039), NETWORKCONF_IPRANGE_RETRIEVE_FAILED("NETWORKCONF_IPRANGE_RETRIEVE_FAILED", 232040), NETWORKCONF_UPDATE_IPRANGE_INCLUDED("NETWORKCONF_UPDATE_IPRANGE_INCLUDED", 232041), NETWORKCONF_VLAN_ID_CREATE_OR_UPDATE_NOT_ALLOWED("NETWORKCONF_VLAN_ID_CREATE_OR_UPDATE_NOT_ALLOWED", 232045), NETWORKCONF_VLAN_ID_DELETE_NOT_ALLOWED("NETWORKCONF_VLAN_ID_DELETE_NOT_ALLOWED", 232046), IPPOOL_IPADDRESS_ASSIGN_FAILED("IPPOOL_IPADDRESS_ASSIGN_FAILED", 233006), IPPOOL_NO_IPADDRESS_AVAILABLE("IPPOOL_NO_IPADDRESS_AVAILABLE", 233008), IPPOOL_ENOUGH_IPADRESS_NOT_AVAILABLE("IPPOOL_ENOUGH_IPADRESS_NOT_AVAILABLE", 233004), IPPOOL_INVALID_GUID("IPPOOL_INVALID_GUID", 233001), INVALID_NAME_LENGTH_CODE("INVALID_NAME_LENGTH_CODE", 234001), INVALID_NAME_FORMAT_CODE("INVALID_NAME_FORMAT_CODE", 234002), INVALID_DESC_LENGTH_CODE("INVALID_DESC_LENGTH_CODE", 234003), INVALID_DESC_FORMAT_CODE("INVALID_DESC_FORMAT_CODE", 234004), INVALID_DISPLAY_NAME_LENGTH_CODE("INVALID_DISPLAY_NAME_LENGTH_CODE", 234015), INVALID_DISPLAY_NAME_FORMAT_CODE("INVALID_DISPLAY_NAME_FORMAT_CODE", 234016), INVALID_IPADDRESS_CODE("INVALID_IPADDRESS_CODE", 234022), INVALID_IPRANGE_CODE("INVALID_IPRANGE_CODE", 234024), INVALID_IPRANGE_SIZE_CODE("INVALID_IPRANGE_SIZE_CODE", 234025);

    private Integer id;
    private String value;


    private ErrorCodeEnum(String value, Integer id) {
        this.value = value;
        this.id = id;
    }


    /* (non-Javadoc)
     * @see com.dell.isg.smi.commons.elm.messaging.IMessageEnum#getValue()
     */
    @Override
    public String getValue() {
        return this.value;
    }


    /* (non-Javadoc)
     * @see com.dell.isg.smi.commons.elm.messaging.IMessageEnum#getId()
     */
    @Override
    public Integer getId() {
        return this.id;
    }


    /* (non-Javadoc)
     * @see java.lang.Enum#toString()
     */
    @Override
    public String toString() {
        return this.value;
    }
}