/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 01:23:39 PM CST
//

package com.dell.isg.smi.virtualnetwork.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The Class ExportIpPoolData.
 */
@ApiModel(value = "ExportIpPoolData", description = "A data transfer object for containing exported IPAddressPoolEntry data with additional audit column information")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ExportIpPoolData")
public class ExportIpPoolData extends IpAddressPoolEntry {

    @ApiModelProperty(value = "Currently not being set with data", dataType = "string", required = true)
    @XmlAttribute(name = "targetName")
    protected String targetName;

    @ApiModelProperty(value = "Last modified by", required = true)
    @XmlAttribute(name = "lastModifiedBy")
    protected String lastModifiedBy;

    @ApiModelProperty(value = "Last modified date", required = true)
    @XmlAttribute(name = "lastModifiedDate")
    protected String lastModifiedDate;


    /**
     * Gets the value of the targetName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTargetName() {
        return targetName;
    }


    /**
     * Sets the value of the targetName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }


    /**
     * Gets the value of the lastModifiedBy property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }


    /**
     * Sets the value of the lastModifiedBy property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLastModifiedBy(String value) {
        this.lastModifiedBy = value;
    }


    /**
     * Gets the value of the lastModifiedDate property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLastModifiedDate() {
        return lastModifiedDate;
    }


    /**
     * Sets the value of the lastModifiedDate property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLastModifiedDate(String value) {
        this.lastModifiedDate = value;
    }

}
